app:
  port: 5678
  root: "../sources"
  release: "../release"
  sources: "source"
  sass_source: "themes/www/code/lib/framework"
  sass_target: "themes/www/source/lib/framework"
  projects_source: "../../../../../public"
  projects_target: "source/_projects"

filters:
  sass:
    - "source/**/*.sass"
    - "source/**/*.scss"
  app:
    - "scaffolds/**/*"
    - "source/**/*"
    - "themes/**/*"
    - "_*.yml"
  projects:
    - "**/README.md"
    - "!**/releases/**"
    - "!**/resume/**/*"
    - "!**/prototypes/**/*" # standard project folders
    - "!**/sources/**/*" # standard project folders
    - "!**/release/**/*" # standard project folders
    - "!**/scripts/**/*" # standard project folders
  ignore:
    - "!**/.**/**/*"
    - "!**/.*"
    - "!**/node_modules/**/*"
    - "!**/bower_components/**/*"
