# Hugo paths
root:
  app: "../sources"
  projects: "../../../../../public"

app:
  config: ""
  config_server: "_server.yml"
  config_builder: "_builder.yml"
  port: 5678
  release: "../release/www"
  sources: "/sources"
  projects: "/sources/_projects"

filters:
  sass:
    - "sources/**/*.sass"
    - "sources/**/*.scss"
  app:
    - "scaffolds/**/*"
    - "sources/**/*"
    - "themes/**/*"
    - "_*.yml"
  projects:
    - "**/README.md"
    - "!**/releases/**"
    - "!**/resume/**/*"
    - "!**/prototypes/**/*" # standard project folders
    - "!**/sources/**/*" # standard project folders
    - "!**/release/**/*" # standard project folders
    - "!**/scripts/**/*" # standard project folders
  ignore:
    - "!**/.**/**/*"
    - "!**/.*"
    - "!**/node_modules/**/*"
    - "!**/bower_components/**/*"
