# Hugo paths
HUGO:
  port: 4000
  root: "/Users/sysuser/Google Drive/folio/public/code/htko/site-base/release"
  public: "/public"
  source: "/source"
  static: "/static/static"
  content: "/static/content"
  watch:
    - "/data/**/*"
    - "/layouts/**/*"
    - "/static/**/*"
    - "/*.yml"
    - "/**/!.**/*"
    - "/**/!.*"
  js_filter:
    - "/js/app.js"
    - "/js/!(app).js"
