# Hugo paths
hugo:
  baseUrl: "http://htko.ca/"
  tempUrl: "http://localhost:5678/"
  port: 5678
  public: "/public"
  source: "/source"
  static: "/static/static"
  content: "/static/content"
  projects: "/static/content/project"

root:
  hugo: "../release/htko"
  projects: "../../../../../public"

filters:
  hugo:
    - "archetypes/**/*"
    - "data/**/*"
    - "layouts/**/*"
    - "static/**/*"
    - "config.yml"
    # - "public/**/*" # feedback loop
  projects:
    - "**/README.md"
    - "!**/free-code-camp/* - */**"
    - "!**/releases/**"
    - "!**/resume/**/*"
    - "!**/prototypes/**/*" # standard project folders
    - "!**/sources/**/*" # standard project folders
    - "!**/release/**/*" # standard project folders
    - "!**/scripts/**/*" # standard project folders
  ignore:
    - "!**/.**/**/*"
    - "!**/.*"
    - "!**/node_modules/**/*"
    - "!**/bower_components/**/*"
