if: branch = master
language: bash

addons:
  ssh_known_hosts: 
    - htko.ca:8022

before_deploy:
- openssl aes-256-cbc -K $encrypted_fc6c684849e9_key -iv $encrypted_fc6c684849e9_iv -in id_rsa_travis.enc -out /tmp/id_rsa_travis -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa_travis
- ssh-add /tmp/id_rsa_travis

deploy:
  provider: script
  skip_cleanup: false
  script: ssh sysuser@htko.ca -p 8022 "cd ~/portfolio/site-htko && git pull && docker-compose up -d --force-recreate"
  on:
    branch: master