baseurl = "http://localhost:1313/"
title = "My New Hugo Site"
languageCode = "en-us"
theme = "foundation"

#Bootstrap Theme
paginate = 5

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"

[params]
  author = "Your Name"
  description = "A simple Hugo theme based on the Bootstrap v4 blog example."
  date_format = "Mon Jan 02, 2006"

[params.sidebar]
  about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

[params.social]
  twitter = "username"

[params.sharingicons]
  hide = false
