baseurl = "http://localhost:4000/"
title = "My New Hugo Site"
languageCode = "en-us"
theme = "Hugo-Theme-Foundation6-Blog"

#Bootstrap Theme
paginate = 5

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"

[params]
  author = "Your Name"
  description = "A simple Hugo theme based on the Foundation v6 blog (w/ sidebar) example."
  date_format = "Mon Jan 02, 2006"

[params.sidebar]
  about = "A simple [Hugo](https://gohugo.io) theme based on the [Foundation v6 blog (w/ sidebar) example](http://foundation.zurb.com/templates-previews-sites-f6/blog.html)."

[params.social]
  twitter = "username"

[params.sharingicons]
  hide = false
