# Metadata
  languageCode = "en-us"
  title = "Hei Tony Ko"
  author = "Tony Ko"
  copyright = "Copyright - Tony Ko. All rights reserved."

# Config
  baseurl = "http://localhost:4000/"
  theme = ""
  canonifyurls = true
  paginate = 3
  disqusShortname = "xxxxxx"
  googleAnalytics = "UA-XXXXXXX-1"

# Params
  [params]
    subtitle = "Personal Portfolio"

  [params.widgets]
    recent_articles = true
    tags = true
    tag_cloud = true
    topics = true

# Taxonomies
  [taxonomies]
    tag = "tags"
    topic = "topics"

# Menus
  # Main
    [[menu.main]]
      name = "Code"
      pre = "<i class='fa fa-folder-open'></i>"
      url = "/topics/code/"

    [[menu.main]]
      name = "Interior Design"
      pre = "<i class='fa fa-folder-open'></i>"
      url = "/topics/interior design/"

    [[menu.main]]
      name = "Photography"
      pre = "<i class='fa fa-folder-open'></i>"
      url = "/topics/photography/"

  # Links
    [[menu.links]]
      name = "Contact"
      pre = "<i class='fa fa-info-circle'></i>"
      url = "/page/contact/"

  # Footer
    [[menu.footer]]
      name = "DISCLAIMER"
      url = "/page/disclaimer/"

    [[menu.footer]]
      name = "LICENSE"
      url = "/page/license/"
