# Metadata
baseurl = "http://localhost:4000/"
languageCode = "en-us"
title = "My New Hugo Site"
author = "Tony Ko"
copyright = "Copyright - Tony Ko. All rights reserved."
canonifyurls = true
paginate = 3
disqusShortname = "xxxxxx"
googleAnalytics = "UA-XXXXXXX-1"

# Config
theme = ""

# mmrath
[[menu.main]]
  name = "TAGS"
  pre = "<i class='fa fa-tags'></i>"
  weight = -110
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "CATEGORIES"
  pre = "<i class='fa fa-folder-open'></i>"
  weight = -100
  identifier = "categories"
  url = "/categories/"

[[menu.main]]
  name = "Contact"
  pre = "<i class='fa fa-info-circle'></i>"
  weight = -90
  identifier = "contact"
  url = "/page/contact"

[[menu.footer]]
  name = "DISCLAIMER"
  weight = -110
  identifier = "disclaimer"
  url = "/page/disclaimer/"

[[menu.footer]]
  name = "LICENSE"
  weight = -120
  identifier = "license"
  url = "/page/license/"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true
