version: '3.5'

services:
  site-htko:
    container_name: site-htko
    image: nginx:1.15.2
    restart: always
    networks:
      - frontend
    volumes:
      - ./release:/usr/share/nginx/html:ro
    labels:
      traefik.port: '80'
      traefik.frontend.rule: 'Host:www.htko.ca'
  site-htko-redirect:
    container_name: site-htko-redirect
    image: schmunk42/nginx-redirect
    restart: always
    networks:
      - frontend
    labels:
      traefik.port: '80'
      traefik.frontend.rule: 'Host:htko.ca'
    environment:
      SERVER_REDIRECT: 'www.htko.ca'
      SERVER_REDIRECT_SCHEME: 'https'

networks:
  frontend:
    external: true