version: '2'
services:
  code-htko-site:
    container_name: code-htko-site
    image: nginx:1.15.2
    restart: always
    network_mode: bridge
    volumes:
      - ./release:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:htko.ca,www.htko.ca"
      - "traefik.frontend.redirect.regex=^http(s?)://www.htko.ca/(.*)"
      - "traefik.frontend.redirect.replacement=https://htko.ca/$${2}"
      - "traefik.frontend.redirect.entryPoint=https"