version: '3.5'

services:
  site-htko:
    container_name: site-htko
    image: nginx:1.15.2
    restart: always
    networks:
      - frontend
    volumes:
      - ./release:/usr/share/nginx/html:ro
    labels:
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: 'www.htko.ca'

networks:
  frontend:
    external: true