version: '2'
services:
  site-htko:
    container_name: site-htko
    image: nginx:1.15.2
    restart: always
    network_mode: bridge
    volumes:
      - ./release:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:htko.ca,www.htko.ca"
      - "traefik.frontend.redirect.regex=^(https://|http://(www.)?)(<path>.*)"
      - "traefik.frontend.redirect.replacement=https://www.$${path}"