# Header
menu:
  code:
    title: Code
    link: code.html
    icon: fa-code
  gfx:
    title: GFX
    link: gfx.html
    icon: fa-paint-brush
  interior-design:
    title: Interior Design
    link: interior-design.html
    icon: fa-university
links:
  github:
    title: GitHub
    link: https://github.com/htkoca/
    icon: fa-code-fork
  linkedin:
    title: LinkedIn
    link: https://linkedin.com/in/htkoca/
    icon: fa-linkedin
  about-me:
    title: About Me
    link: about-me.html
    icon: fa-id-card-o

# Miscellaneous
rss: /atom.xml
google_analytics:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
