# Header
menu:
  code:
    title: Code
    link: code/
    icon: fa-code
  gfx:
    title: GFX
    link: gfx/
    icon: fa-paint-brush
  interior-design:
    title: Interior Design
    link: interior-design/
    icon: fa-university
links:
  github:
    title: GitHub
    link: github/
    icon: fa-code-fork
  linkedin:
    title: LinkedIn
    link: linkedin/
    icon: fa-linkedin
  about-me:
    title: About Me
    link: about-me/
    icon: fa-id-card-o

rss: /atom.xml

# Miscellaneous
google_analytics:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
