---
# Metadata
languageCode        : "en-us"
title               : "Tony Ko | Personal Portfolio"
author              : "Tony Ko"

# Params
params:
  cover             : "content/project/gfx/personal/htko-identity/assets/mockup-cards.jpg"
  subtitle          : "Tony Ko"
  copyright         : "Copyright - Tony Ko."
  description       : "Personal Portfolio of Tony Ko, Front End Developer."
  locale            : "en_US"
  google_verify     : ""
  facebook          : "htko89"
  facebook_admin    : "htko89"
  facebook_app_id   : ""

# Config
canonifyurls        : true
Paginate            : 16
disqusShortname     : "xxxxxx"
googleAnalytics     : "UA-XXXXXXX-1"
contentDir          : "static/content"
ignoreFiles:
  - "\\.html$"
  - "\\.png$"
  - "\\.jpg$"
  - "\\.jpeg$"
  - "\\.svg$"

# Taxonomies
taxonomies:
  topic             : "topics"
  tool              : "tools"
  category          : "categories"
  tag               : "tags"

# Menus
menu:
  main:
    - name          : "Code"
      identifier    : "code"
      pre           : "fa-code"
      url           : "/topics/code/"
      weight        : 1
    - name          : "GFX"
      identifier    : "gfx"
      pre           : "fa-paint-brush"
      url           : "/topics/gfx/"
      weight        : 2
    - name          : "Interior Design"
      identifier    : "interior-design"
      pre           : "fa-bank"
      url           : "/topics/interior design/"
      weight        : 3
    # - name          : "Photography"
    #   identifier    : "photography"
    #   pre           : "fa-camera-retro"
    #   url           : "/topics/photography/"
    #   weight        : -110
  links:
    # - name          : "Blog"
    #   identifier    : "blog"
    #   pre           : "fa-bookmark-o"
    #   url           : "/categories/blog"
    #   weight        : -110
    - name          : "About Me"
      identifier    : "about-me"
      pre           : "fa-user-circle-o"
      url           : "page/about-me/README/"
      weight        : 1
  footer:
    - name          : "Github"
      identifier    : "github"
      pre           : "fa-code-fork"
      url           : "https://github.com/htko89"
      weight        : 1
    - name          : "Linkedin"
      identifier    : "linkedin"
      pre           : "fa-linkedin"
      url           : "http://lnked.in/htko89"
      weight        : 2
    - name          : "Resume"
      identifier    : "resume"
      pre           : "fa-id-card-o"
      url           : "http://htko.ca/resume.pdf"
      weight        : 3
...
