name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.vercel-deploy.outputs.deploy-url }}
    steps:
      # Setup CLI & Dependencies
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install local dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Install global dependencies
        run: pnpm install -g vercel@latest

      # Pre build test
      - name: Run Tests against CI build
        run: pnpm run test

      # Build & Deploy Artifacts
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy
        run: echo "::set-output name=deploy-url::$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})"

      # Post build test
      - name: Run Tests against Vercel build
        run: pnpm run test
        env:
          VERCEL_URL: ${{ steps.vercel-deploy.outputs.deploy-url }}

